//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoRest
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_usuarios
    {
        public int id_usuario { get; set; }
        public string nm_usuario { get; set; }
        public string ds_login { get; set; }
        public string ds_senha { get; set; }
        public string fl_tipo { get; set; }
        public string fl_ativo { get; set; }
        public int cd_setor { get; set; }
    }
}
